sudo: required

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - m4
      - valgrind

install:
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -xvzf bison-3.0.4.tar.gz
  - cd bison-3.0.4
  - ./configure --prefix=/usr/local/bison
  - sudo make install
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake -DBISON_EXECUTABLE=/usr/local/bison/bin/bison ..

script: make && make test

notifications:
  email: false

